# A Starter config file
# Naming follows ccxt naming conventions
# Visit https://github.com/ccxt/ccxt/wiki/manual#symbols-and-market-ids
exchanges:
  binance:
    # Override ccxt exchange properties
    # and exchange specific options
    properties:
      "enableRateLimit": True
      "async_support": True
      "newUpdates": True
      "verbose": False
      "timeout": 10000
      "options":
        {}

    symbols:
      "BTC/USD:BTC":
        streams:
            watchOHLCV:
              options: {}
            watchTicker:
              options: {}
            watchTrades:
              options: {}
            watchOrderBook:
              options: {}
      "BTC/USDT:USDT":
        streams:
            watchOHLCV:
              options: {}
            watchTicker:
              options: {}
            watchTrades:
              options: {}
            watchOrderBook:
              options: {}

  bitmex:
    # Override ccxt exchange properties
    # and exchange specific options
    properties:
      "enableRateLimit": True
      "async_support": True
      "newUpdates": True
      "verbose": False
      "timeout": 10000

    symbols:
      "BTC/USD:BTC":
        streams:
            watchOHLCV:
              options: {}
            watchTicker:
              options: {}
            watchTrades:
              options: {}
            watchOrderBook:
              options: {}
      "BTC/USDT:USDT":
        streams:
            watchOHLCV:
              options: {}
            watchTicker:
              options: {}
            watchTrades:
              options: {}
            watchOrderBook:
              options: {}